kind: pipeline
type: docker
name: professional-website

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kuzimoto/professional-website
      tags: latest