kind: pipeline
type: docker
name: professional-website

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: kuzimoto/professional-website
    tags: latest
    recursive: true